### ISSUE TITLE
Error: Cannot find module './generate-config-schema.ts' [BUG]

### ISSUE THREAD

**Issue by iakzs** [onesoft-sudo/sudobot#147]
I tried to generate the JSON config schema files using the following command:
`$ sudo npx ts-node scripts/generate-config-schema.ts`

And I got an error saying
```
$ sudo npx ts-node scripts/generate-config-schema.ts
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module './generate-config-schema.ts'
Require stack:
- /home/koslzishotaf/hm/sudobot/scripts/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at requireResolveNonCached (/home/koslzishotaf/hm/sudobot/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/home/koslzishotaf/hm/sudobot/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/home/koslzishotaf/hm/sudobot/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/home/koslzishotaf/hm/sudobot/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/koslzishotaf/hm/sudobot/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/koslzishotaf/hm/sudobot/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/koslzishotaf/hm/sudobot/scripts/imaginaryUncacheableRequireResolveScript'
  ]
}

```

**Comment by virtual-designer** [comment]
Hello, thanks for reporting this issue! Recently we've rewritten the scripts in pure JavaScript, so changing your command to the following should work:

```
node scripts/generate-config-schema.js
```

Also, you probably don't need `sudo` before the command.

You've probably seen this in the documentation, I apologize for the confusion. The documentation needs to be updated. I'll update it in the next 24 hours.

**Comment by iakzs** [comment]
Hello, thanks for your response! I've got another error, 

```
$ node scripts/generate-config-schema.js
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '../build/services/ConfigManager'
Require stack:
- /home/koslzishotaf/HoyoMusk_the_cooker/sudobot/scripts/generate-config-schema.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/koslzishotaf/HoyoMusk_the_cooker/sudobot/scripts/generate-config-schema.js:27:31)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/koslzishotaf/HoyoMusk_the_cooker/sudobot/scripts/generate-config-schema.js'
  ]
}

Node.js v20.5.1
```

**Comment by virtual-designer** [comment]
> Hello, thanks for your response! I've got another error, 
> 
> ```
> $ node scripts/generate-config-schema.js
> node:internal/modules/cjs/loader:1051
>   throw err;
>   ^
> 
> Error: Cannot find module '../build/services/ConfigManager'
> Require stack:
> - /home/koslzishotaf/HoyoMusk_the_cooker/sudobot/scripts/generate-config-schema.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
>     at Module._load (node:internal/modules/cjs/loader:901:27)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at require (node:internal/modules/helpers:130:18)
>     at Object.<anonymous> (/home/koslzishotaf/HoyoMusk_the_cooker/sudobot/scripts/generate-config-schema.js:27:31)
>     at Module._compile (node:internal/modules/cjs/loader:1233:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
>     at Module._load (node:internal/modules/cjs/loader:938:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/koslzishotaf/HoyoMusk_the_cooker/sudobot/scripts/generate-config-schema.js'
>   ]
> }
> 
> Node.js v20.5.1
> ```
> 

Seems like you've forgotten to build the bot! Run `npm run build` to build the JavaScript files first and then you can use the script.

**Comment by iakzs** [comment]
Thanks! It works now!

**Comment by virtual-designer** [comment]
> Thanks! It works now!

I will still keep this issue open for now, so that I don't forget to update the documentation.

**Comment by virtual-designer** [comment]
Fixed.
